crc-org/crc-extension

src/crc-cli.ts, src/detection-checks.ts, src/extension.ts
This is a copy of https://github.com/containers/podman-desktop/pull/1487
It adds CRC CLI detection checks, add show them on dashboard.
related to https://github.com/containers/podman-desktop/issues/1439
Just run without CRC installed and you should see detection checks, like on screenshot
=> feat: add crc cli detection checks

src/install/base-install.ts, src/install/win-install.ts
If user cancel installation on windows, we don't need to show error message.
Also this PR change download status bar item logging, by removing mention of downloading sha checksum, and add `Donloading: 0%` instead.
=> fix: handling win installer exit code

package.json, rollup.config.js, scripts/run.mjs, src/crc-cli.ts, src/crc-setup.ts, src/crc-start.ts, src/crc-status.ts, src/daemon-commander.ts, src/extension.ts, src/install/crc-install.ts, src/log-provider.ts, tsconfig.json
Fixes #18
This PR add check if pullsecret is missing during vm start:
And it add basic validation, it just check that provided value is valid JSON:
>Also this PR provided various refactoring.
=> Ask pull secret during start

src/crc-delete.ts, src/extension.ts, src/util.ts, yarn.lock
This PR add `Delete` tray menu item.
Demo:
https://user-images.githubusercontent.com/929743/227254873-048c6183-5460-4574-a6d9-5b168713c543.mp4
Message when no cluster exist:
Depends on https://github.com/containers/podman-desktop/pull/1800
=> add delete tray item

src/crc-delete.ts, src/crc-stop.ts, src/extension.ts
This PR add k8's connection lifecycle object(start, stop and delete).
Will be used with https://github.com/containers/podman-desktop/issues/1337
=> add k8s connection lifecycle

package.json, src/constants.ts, src/daemon-commander.ts, src/logger.ts, src/preferences.ts
This PR remove default and minimum values from crc-extension configuration.
Add validation of configuration property based on current preset.
Also it inform and assist user recreate instance when preset changed.
And PR add proxy setting sync, but in case of proxy settings we copy setting from podman-desktop to crc.
Resolves https://github.com/crc-org/crc-extension/issues/32
Demo:
https://user-images.githubusercontent.com/929743/229790494-b87f9224-e4f4-4bef-812f-05128f50c62a.mov
=> Enhance configuration sync and validation

.vscode/launch.json, scripts/run.mjs
Just use `Debug Podman-Desktop Process` to launch podman desktop with crc-extenson.
If you use this, meke sure to delete `<home>/.local/share/containers/podman-desktop/plugins/openshift-local` folder.
=> Add vscode launch config to debug extension

src/command.ts, src/extension.ts, src/login-commands.ts
Demo:
https://user-images.githubusercontent.com/929743/232708809-01596bde-7bad-4e75-b52d-1ce09b873360.mov
PR also fixes https://github.com/crc-org/crc-extension/issues/46
Note: `Copy*` commands are shown only for `OpenShift` preset as `MicroShift` doesn’t provide necessary information
=> Add OC login copy commands

src/crc-status.ts, src/daemon-commander.ts, src/extension.ts, src/preferences.ts
This PR add check for `crc setup` state, and if crc requires to call `setup`, it propose to do that with `initialise` button on dashboard.
Related issue https://github.com/crc-org/crc-extension/issues/39
Demo:
https://user-images.githubusercontent.com/929743/233959694-8f339b94-46fc-4d7d-ade0-b8f3e1a6cc22.mp4
=> Propose to initialise if setup not finished

src/dev-terminal.ts
For the `microshift` preset it is preferred to use the `oc` command to interact with the API. We missed adding this check to match the OpenShift usage.
=> Allow `oc-env` to be used with the `microshift` preset

Dockerfile, package.json
Aligned the publisher/vendor name of the extension container and the package identifier are referencing the same
=> Make sure the publisher name is consistent

src/crc-status.ts, src/extension.ts
This PR add `configured` state for provider, which allow to start crc from dashboard:
Fix https://github.com/crc-org/crc-extension/issues/64
Depends on https://github.com/containers/podman-desktop/pull/2304
=> add 'configured' state

package.json
Replaces #86
Minor improvements to the extension description and preferences:
- Updated extension description. It is a bit bland, but shorter/concise and matches other extensions more.
- Used markdown to change link to pull secret into a real link. Easier to copy for now; will be clickable once [1] is fixed.
[1] https://github.com/containers/podman-desktop/issues/2230
=> Improve description and preferences

src/crc-setup.ts
This fixes #74
Removed the placeholder text and replaced with a temporary solution. Also, the preset is stylized to represent the product names.
=> Changed preset text

src/crc-setup.ts, src/extension.ts
Fixes #67 
Currently we do not support the podman preset, 'focus' on OpenShift and MicroShift, as decided at the F2F. This means we need to tell the user we would have to change the preset to work correctly. The current text is temporary until we have a better solution, like markdown formatted or decided to implement support.
=> Fixes #67 Shows infoDialog when podman preset is used

src/crc-setup.ts, src/crc-start.ts
Temporary solution to add an informational dialog before the pull-secret input.
=> Fixes #56 Alternative pull-secret info dialog

README.md
Depending on how this is rendered, like on GitHub, a copy to clipboard button is shown.
=> Minor update to container name

src/crc-start.ts, src/install/win-install.ts
=> fix: Dialogs are sometimes concealed

src/extension.ts
That fix adding commands in a tray with `temp` provider.
So we will add commands only if crc cli is installed.
=> Register commands only if crc installed

.dockerignore
if these two directories are copied to the build container, i got the following errors while using `podman-remote` to build:
```
[!] Error: EACCES: permission denied, open '/opt/app-root/src/dist/extension.js'
Error: EACCES: permission denied, open '/opt/app-root/src/dist/extension.js'
```
```
[3/5] Fetching packages...
error An unexpected error occurred: "EACCES: permission denied, unlink '/opt/app-root/src/node_modules/.yarn-integrity'".
info If you think this is a bug, please open a bug report with the information provided in "/opt/app-root/src/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: building at STEP "RUN npm install -g yarn     && npx yarn install     && npx yarn build": while running runtime: exit status 1
```
=> build: add .dockerignore to skip copying node_modules and dist

README.md
Updated the location of the installation field to **Settings > Extensions**.
The location **Settings > Destkop Extensions** was leading to installation error: Image `quay.io/redhat-developer/openshift-local-extension:latest is not a Docker Desktop Extension`
=> Update installation procedure

Dockerfile
=> Single layer extension container

src/extension.ts, yarn.lock
Fix #122 
Demo:
https://github.com/crc-org/crc-extension/assets/929743/c65a740e-7f04-4df7-a5e3-6c27d693e312
=> Remove connection factory when crc has instance

src/crc-setup.ts, src/util.ts
This PR changes default preset suggestion for setup process to `microshift`.
Also it remove `experimental` label from `microshift` preset description.
=> Make microshift extension default preset

src/crc-cli.ts
Due to a strict check of a `hidden_daemon.ps1` file content during `crc setup` on `crc` side there is an error when initializing the CRC in podman desktop. This PR should align the default windows `crc` executable location with this strict check.
Fixes #175
=> Start Windows CRC executable path with upper case drive-letter

.github/workflows/pr-check.yaml
podman-desktop needs node 18, trying to build with node 16 shows the following error:
```
error podman-desktop@1.5.0-next: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.14.2"
```
=> bump to node 18 for github actions workflow

src/extension.ts, src/install/win-install.ts
=> Show Full User Experience When Running The Installer On Windows

__mocks__/@podman-desktop/api.js, package.json, src/crc-setup.spec.ts, src/crc-setup.ts, src/crc-start.spec.ts, src/crc-start.ts, src/crc-status.ts, src/extension.ts, vitest.config.js, yarn.lock
This PR removes the isNeedSetup variable which is used to decide if crc has already been set up or we need to perform it. However that variable is misleading because its value is not always refreshed. By removing it we can be sure that, when needed, we exactly know if the daemon is running or not. 
This fixes https://github.com/crc-org/crc-extension/issues/205
=> fix: make sure the crc daemon is running before execute start (#205)"

src/extension.ts
This PR removes the registration of the provider lifecycle which is responsible of showing the buttons on the header of the creation page. See #203 .
The start/stop actions assigned to the provider lifecycle are the same attached to the connections lifecycle. So it looks like the registration of the provider lifecycle is actually useless.
=> fix: remove provider lifecyle

.github/workflows/build-builder.yaml, oci/Containerfile.builder
This PR will add the Containerfile require to build the cache builder which will be used as part of the multistage building strategy.
=> Add an oci image to act as a cache builder for a multistage building strategy

.github/workflows/release.yaml, oci/Containerfile.multistage
=> Build strategy based on containers with cache

.extfiles, package.json, scripts/build.cjs, vite.config.js, yarn.lock
=> fix: migrate build from rollup to vite

package.json
The values that are within the package.json are the ones that are used by podman desktop to generate the range of the sliders. Because the max value is in bytes, we also have to use bytes for the minimum.
However CRC expects bits values. So the minimum memory value accepted by CRC for microshift is 4096 MiB converted to bytes 4294967296.
Same calculation has been made for the rest.
This is somehow part of https://github.com/crc-org/crc-extension/issues/243 bc with the current values you could set an invalid memory amount. The minimum was  4000000000 bytes that converted to Mib are 3814, which is less than the minimum accepted 4096
=> fix: set correct minimum memory values in package.json

src/crc-status.ts
```
$ npx tsc --noEmit
../crc-extension/src/crc-status.ts:65:21 - error TS2769: No overload matches this call.
Overload 1 of 2, '(intervalId: string | number | Timeout): void', gave the following error.
Argument of type 'Timer' is not assignable to parameter of type 'string | number | Timeout'.
Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.
Overload 2 of 2, '(id: number): void', gave the following error.
Argument of type 'Timer' is not assignable to parameter of type 'number'.
65       clearInterval(this.updateTimer);
~~~~~~~~~~~~~~~~
../crc-extension/node_modules/@types/node/timers.d.ts:130:17
130                 [Symbol.dispose](): void;
~~~~~~~~~~~~~~~~
'[Symbol.dispose]' is declared here.
Found 1 error in ../crc-extension/src/crc-status.ts:65 …
```
=> fix: typescript typecheck error

src/extension.ts
This commit fixes condition for running initialization. It was  incorrectly changed when refactoring extension activation code.
Fix #252.
=> fix: run crc initialization after cleanup

.github/workflows/release.yaml
Task that creates PR cannot be used right now because of missing permissions for github actions. I'll send PR to increment version manually.
=> fix: remove step that creates PR to increment the version

.github/workflows/release.yaml
This reverts commit 71c8e96b143dcabd9c5cbe0cd9921be9cada5bb6.
Github actions should have `create and approve PR` permission for this change to work properly.
=> fix: revert "fix: remove step that creates PR to increment the version"

tests/src/openshift-local-extension.spec.ts
=> chore(tests): add check for settings/preferences assets

.github/workflows/e2e-main.yml, .github/workflows/pr-check.yaml, tests/src/openshift-local-extension.spec.ts
=> Extend the E2E tests to be run on windows

.github/workflows/e2e-main.yml, .github/workflows/pr-check.yaml
=> test(e2e): crc-extension e2e tests runner for mac
