- .gitignore
- package.json
- scripts/build.js
- scripts/download.mts
- scripts/run.mjs
- src/crc.json
- src/extension.ts
- src/install/base-install.ts
- src/install/crc-install.ts
- src/install/win-install.ts
- src/util.ts
- tsconfig.json
- yarn.lock
This PR add installation of CRC on windows.
>Note: This PR bundle crc installer with crc-extension, so installation could be offline.
Demo:
https://user-images.githubusercontent.com/929743/224037074-1357910b-50fb-48f9-91ed-4b83ba70ae0f.mp4
> feat: install crc on windows

- package.json
- scripts/download.mts
- src/install/crc-install.ts
- src/install/mac-install.ts
- yarn.lock
This PR add crc installation on macos
https://user-images.githubusercontent.com/929743/224253865-cd1a9750-bef4-40e7-9ad8-75cf0938a98a.mp4
> feat: add macos crc installer

- src/crc-setup.ts
> Use information dialog to select preset

- package.json
- src/crc-delete.ts
- src/crc-start.ts
- src/daemon-commander.ts
- src/extension.ts
- src/preferences.ts
- src/util.ts
- yarn.lock
This PR brings synchronisation of the preferences/configuration between crc-extension and crc CLI.
On extension start we reed configuration of crc CLI and update extension preferences.
When user change extension preference from UI, we check that crc configuration is not change, if it changed we ask user what to do.
Demo:
https://user-images.githubusercontent.com/929743/228148052-4134454a-f86f-45ec-84de-ed7ed4998ca1.mp4
> sync crc and extension preferences

- src/crc-setup.ts
- src/install/base-install.ts
PR add more info during `setup`:
https://user-images.githubusercontent.com/929743/228843673-cbf0b9bd-e6af-4a7f-8268-ba76e4e5fcfb.mp4
>Note Do not merge until next (2.16.0) crc release, as PR relying on new param `--show-progressbars`
> Parse Uncompressing output during setup

- README.md
- package.json
from `OpenShift Local` to `Red Hat OpenShift Local`
> Change displayed name

- .github/workflows/release.yaml
> fix image name

- package.json
- src/command.ts
- src/crc-console.ts
- src/crc-delete.ts
- src/dev-terminal.ts
- src/extension.ts
- yarn.lock
PR also defines new way to handle tray items, with manipulating their enabled state.
Demo:
https://user-images.githubusercontent.com/929743/231715248-90e08b7d-3475-43a3-acd3-00f23eb7f8a6.mov
> Add open openshift console command

- package.json
Remove the `(Optional)` remark for the pull-secret
> Remove 'optional' remark for the pull-secret

- src/crc-cli.ts
- src/extension.ts
Now it PD resource page should always show start/stop/restart/delete buttons for CRC:
Also this PR delete code which try to launch crc daemon from extension, now we fully rely on `crc setup`
> Fix k8s connection creation, remove daemon start

- package.json
- src/extension.ts
- src/image-handler.ts
- src/podman-cli.ts
- yarn.lock
Resolve https://github.com/crc-org/crc-extension/issues/61
Demo:
https://user-images.githubusercontent.com/929743/236190360-eafba14c-1119-4bda-859e-6feb62104ba7.mp4
After successful upload it show notification:
> Add command to push image to crc cluster

- src/crc-status.ts
- src/preferences.ts
Demo:
https://user-images.githubusercontent.com/929743/236415001-cd394606-0133-4b78-b021-4170d5e4e7fa.mov
Fix https://github.com/crc-org/crc-extension/issues/76
Node: UI doesn’t update, but it PD issue
Also crc has strange behaviour on CPUS, when I switch preset, it keeps CPU configuration, so only RAM is changed.
> Update preference on preset change

- README.md
- docs/develop.md
Fixes #71
Preview here: https://github.com/gbraad-redhat/crc-extension/tree/main#red-hat-openshift-local-extension
> Update README with extension documentation

- src/command.ts
- src/crc-console.ts
- src/crc-delete.ts
- src/crc-setup.ts
- src/crc-status.ts
- src/dev-terminal.ts
- src/extension.ts
- src/image-handler.ts
- src/login-commands.ts
Fixes https://github.com/crc-org/crc-extension/issues/72
Also it handle delete properly, so all command for tray remove on delete and added back on create.
Demo:
https://github.com/crc-org/crc-extension/assets/929743/b2564590-f3e2-4b37-abae-422ce53a292c
> Add create crc vm function, and handle delete properly

- src/extension.ts
- src/install/crc-install.ts
Demo:
https://github.com/crc-org/crc-extension/assets/929743/da95e811-75ab-40ac-8b85-a79406206fc1
Related to https://github.com/crc-org/crc-extension/issues/39
> Set installed state even setup is failed

- src/command.ts
- src/constants.ts
- src/crc-cli.ts
- src/crc-status.ts
- src/daemon-commander.ts
- src/extension.ts
- src/install/crc-install.ts
- src/preferences.ts
- src/types.ts
- src/util.ts
Resolve https://github.com/crc-org/crc-extension/issues/99
Demo:
> Show current preset on dashboard

- src/crc-start.ts
- src/extension.ts
- yarn.lock
Also it improve handling situation when pullsecret was not provided. Now it show error, that start not possible without pullsecret.
Demo:
https://github.com/crc-org/crc-extension/assets/929743/187db7bb-ab03-458e-9218-6305a81e5fa1
> Use markdown for pullsecret description

- src/extension.ts
Register connection factory only on installed state, to avoid possibility to create crc connection when crc is not installed.
> Register connection factory only on installed state

- .github/workflows/release.yaml
- Dockerfile
> Use multi-stage container build

- package.json
- scripts/run.mts
Resolves https://github.com/crc-org/crc-extension/issues/8
> Use TS for scripts

- src/daemon-commander.ts
- src/extension.ts
Fix https://github.com/crc-org/crc-extension/issues/135
> Sync preferences even if no crc instance

- src/crc-start.ts
> Add preset info to telemetry:crc.start

- src/extension.ts
- src/util.ts
> Use default preset label if preset is not set

- src/extension.ts
> feat: add markdown description for OpenShift Local

- package.json
> cut release v1.2.0

- package.json
it looks like a copy/paste from other extensions
> chore: cleanup unused example command

- src/image-handler.ts
> fix: show information message after image pushed to the cluster

- src/extension.ts
https://github.com/crc-org/crc-extension/assets/620330/93274566-2660-436a-98be-876573e58841
Fix #229.
> fix: update CRC status after installation or any status change

- src/extension.ts
> fix: updates state during extension startup

- src/extension.ts
> fix: dispose CommandManager on extension deactivation

- package.json
Increment version version of extension before release
> fix: update version to 1.4.0

- src/daemon-commander.ts
> fix: create machine is broken since got update

- README.md
This PR improves the structure of the README document, removes documentation of content that no longer exists, and adds an index of contents and the explanation of installing OpenShift Local from Podman Desktop. This update helps the QE team to test the extension too and closes #312 partially
> [DOC] Update README file

- .github/workflows/e2e-main.yml
- .github/workflows/pr-check.yaml
> test(e2e): add junit test report

- .github/workflows/pr-check.yaml
> test(e2e): step to get latest version of @podman-desktop test framework

- .github/workflows/e2e-main.yml
Actually fixes #485 this time. #486 was missing an step on e2e-main.yml file
> ci(test): missing step e2e-main workflow

- .github/workflows/e2e-main.yml
> test(ci): fix e2e-main.yml
